// @ts-nocheck
export * from "./types/weapp-json-schema/app.json.ts"
export * from "./types/weapp-json-schema/ext.json.ts"
export * from "./types/weapp-json-schema/game.json.ts"
export * from "./types/weapp-json-schema/plugin.json.ts"
export * from "./types/weapp-json-schema/project.config.json.ts"
export * from "./types/weapp-json-schema/project.private.config.json.ts"
export * from "./types/weapp-json-schema/sitemap.json.ts"
export * from "./types/weapp-json-schema/container.config.json.ts"
export * from "./types/weapp-json-schema/theme.json.ts"
export * from "./types/weapp-json-schema/page_component.json.ts"